import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { theme } from "../styles/theme";

import { Heading, Text, Button, ColorModeScript } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Heading as="h1" size="2xl">
          Welcome to Inthanity
        </Heading>
        <Heading as="h2" size="xl">
          Fact: 88% of new business comes from referrals
        </Heading>
        <Text>Let&apos;s make a referral!</Text>
        <Button size="lg" height="200px" width="400px">
          <Heading>Make a Referral</Heading>
        </Button>
      </main>
    </div>
  );
};

export default Home;
