import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ColorModeScript } from "@chakra-ui/react";
import { theme } from "../styles/theme";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <h1 className={styles.title}>Welcome to Inthanity</h1>
      </main>
    </div>
  );
};

export default Home;
